### ISSUE TITLE
Change news to be a carousel for each respective stock. This is a lower priority task but will look nice. See Justin's drawing.

### ISSUE THREAD

**Issue by NoahHodgson** [NoahHodgson/CISC474-stocks4me#52]

**Comment by jwhamilton99** [comment]
<img width="513" alt="Screen Shot 2021-11-30 at 9 36 48 AM" src="https://user-images.githubusercontent.com/54966643/144067204-e913815f-2c05-4105-819d-4d316664dc9f.png">
